download issue report from app.wiz.io and store here

 - path to file is currently hardcoded in filter-vulnerabilities.py
 - replace csvfile = "" with correct path

(this will become a configuration option later on)
